Vagrant.configure("2") do |config|
    config.vm.define "web01" do |web01|
        web01.vm.box = "ubuntu/jammy64"
        web01.vm.box_version = "20241002.0.0"
        web01.vm.hostname = "web01"
        web01.vm.network "private_network", ip: "192.168.56.41"
    end

    config.vm.define "web02" do |web02|
        web02.vm.box = "ubuntu/jammy64"
        web02.vm.box_version = "20241002.0.0"
        web02.vm.hostname = "web02"
        web02.vm.network "private_network", ip: "192.168.56.42"
    end

    config.vm.define "db01" do |db01|
        db01.vm.box = "centos/7"
        db01.vm.hostname = "db01"
        db01.vm.network "private_network", ip: "192.168.56.43"
        db01.vm.provision "shell", inline: <<-SHELL
            yum install wget unzip mariadb-server -y
            systemctl start mariadb
            systemctl enable mariadb
        SHELL
    end
end